apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
data:
  kratos.yaml: |
    dsn: postgres://postgres:hikmah_pass@postgres:5432/hikmah_db?sslmode=disable
    serve:
      public:
        base_url: http://localhost:8080/self-service/
      admin:
        base_url: http://kratos:4434/
    selfservice:
      default_browser_return_url: http://localhost:3000/
      methods:
        password:
          enabled: true
    log:
      level: debug
