apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  labels:
    app: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kratos
  template:
    metadata:
      labels:
        app: kratos
    spec:
      containers:
        - name: kratos
          image: oryd/kratos:v1.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4433 # Public
            - containerPort: 4434 # Admin
          command: ["kratos", "serve", "all", "--config", "/etc/config/kratos/kratos.yml"]
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: DEV
              value: "true"
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/config/kratos
      volumes:
        - name: kratos-config
          configMap:
            name: kratos-config
---
apiVersion: v1
kind: Service
metadata:
  name: kratos
spec:
  ports:
    - name: public
      port: 4433
      targetPort: 4433
    - name: admin
      port: 4434
      targetPort: 4434
  selector:
    app: kratos
