apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - redpanda/redpanda.yaml
  - observability/grafana-stack.yaml
  - identity/kratos.yaml
  - identity/kratos-config.yaml
  - maktba.yaml
  - gateway/gateway.yaml
